### ISSUE TITLE
Rename Entry to Cursor?

### ISSUE THREAD

**Issue by stjepang** [crossbeam-rs/crossbeam-skiplist#2]
One of the questions raised in the RFC discussion was whether we should rename `Entry` to `Cursor` (suggested by @Amanieu).

I'm *slightly* leaning towards `Entry`, but don't feel strongly about it. Any other opinions?

**Comment by Amanieu** [comment]
I don't feel too strongly about it either, though leaning *slightly* towards `Cursor` myself.

**Comment by Amanieu** [comment]
Let's just drop this, it seems that we have settled on `Entry`.
