### ISSUE TITLE
Range search API

### ISSUE THREAD

**Issue by Amanieu** [crossbeam-rs/crossbeam-skiplist#5]
A more general alternative to the existing `search` function.

```rust
#[derive(Clone, Copy, Debug, Hash, PartialEq, Eq)]
pub enum Bound<T> {
    /// An inclusive bound.
    Included(T),
    /// An exclusive bound.
    Excluded(T),
    /// An infinite endpoint. Indicates that there is no bound in this direction.
    Unbounded,
}

impl<K, V> SkipMap<K, V>
where
    K: Ord,
{
    /// Returns an `Entry` pointing to the lowest element whose key is above
    /// the given bound. If no such element is found then `None` is
    /// returned.
    pub fn lower_bound<Q>(&self, bound: Bound<&Q>) -> Option<Entry<K, V>>
    where
        K: Borrow<Q>,
        Q: Ord + ?Sized,
    {}

    /// Returns an `Entry` pointing to the highest element whose key is below
    /// the given bound. If no such element is found then `None` is
    /// returned.
    pub fn upper_bound<Q>(&self, bound: Bound<&Q>) -> Option<Entry<K, V>>
    where
        K: Borrow<Q>,
        Q: Ord + ?Sized,
    {}
}
```

**Comment by stjepang** [comment]
👍 to this idea.

Let's copy [`Bound`](https://doc.rust-lang.org/std/collections/enum.Bound.html) and [`RangeArgument`](https://doc.rust-lang.org/std/collections/range/trait.RangeArgument.html) from the standard library and implement method `range`, too.

Hopefully `Bound` and `RangeArgument` get stabilized soon so we don't have to make our own.

**Comment by Amanieu** [comment]
I'm personally not a big fan of `RangeArgument`. I prefer the old `range(Bound, Bound)` API.

**Comment by stjepang** [comment]
I didn't follow discussions around it, but is it not more general? You can pass `(Bound, Bound)` as a `RangeArgument` so there's nothing to lose right?
